version: "3.8"
services:
  app:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./next-app-bun:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3001
    command: bun run dev
    depends_on:
      - redis
    networks:
      - dev_network

  socket-server:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./next-app-bun:/app
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - SOCKET_PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    command: bun --watch socket-server.ts
    depends_on:
      - redis
    networks:
      - dev_network

  redis:
    image: redis:alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    # No persistence command needed. Default is memory-only/snapshotting.
    restart: unless-stopped
    networks:
      - dev_network

  redis-insight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
