version: "3.8"

services:
  app:
    build:
      context: ./next-app-bun
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" # Web App
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - app_network

  socket-server:
    build:
      context: ./next-app-bun
      dockerfile: Dockerfile.socket
    restart: always
    ports:
      - "3001:3001" # WebSocket server
    environment:
      - REDIS_URL=redis://redis:6379
      - SOCKET_PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:alpine
    restart: always
    # No ports mapped here! It is secure inside the network.
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
